USE Minions;

ALTER TABLE Users
DROP CONSTRAINT PK_Users;

ALTER TABLE Users
ADD CONSTRAINT PK_Users_Id PRIMARY KEY (Id);

ALTER TABLE Users
DROP CONSTRAINT UQ__Users__536C85E496D7177D;

ALTER TABLE Users
ADD CONSTRAINT UQ_Users_Username UNIQUE (Username);