USE Minions;

ALTER TABLE Users
DROP CONSTRAINT DF__Users__IsDeleted__4D94879B;

ALTER TABLE Users
ADD CONSTRAINT DF_Users_IsDeleted_False DEFAULT 0 FOR IsDeleted;

ALTER TABLE Users
ADD CONSTRAINT DF_Users_LastLogin_CURRENT_TIMESTAMP
DEFAULT CURRENT_TIMESTAMP FOR LastLogin;